name: student_1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.5
  dio: ^5.5.0+1
  draggable_home: ^1.0.5
  file_picker: ^8.0.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  hidable: ^1.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  media_picker_widget: ^1.0.7
  motion_tab_bar: ^2.0.4
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  responsive_framework: ^1.4.0
  riverpod: ^2.5.1
  sidebar_bigeagle: ^0.2.2+1

  path_provider: any

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true  # Add this line


  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/finalbg.png 
    - assets/images/bg3.jpg
    - assets/images/teacher1.jpg
    - assets/images/teacher2.jpg