name: ai_based
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.13
  flutter_gemini: ^2.0.4
  flutter_launcher_icons: ^0.13.1
   
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  google_generative_ai: ^0.4.2
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/splash_background.jpg

